# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Lime
subtitle: 一个简朴、易读、响应式的网站主题。
description: 本主题由欧雷于 2015 年开始设计与开发，并在个人网站「欧雷流」及个人各种开源软件的文档站上使用多年；在设计时以提高阅读体验和保持简洁风格为最高原则，体现个性在其次。适用于博客、个人网站、API 文档站等以内容为主的网站。
keywords:
author: 欧雷
language: zh-CN
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://example.io
permalink: posts/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false
  trailing_html: false

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: true
prismjs:
  enable: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: '/'
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: false

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: lime-local
theme_config:
  meta:
    url: https://lime-theme.github.io
  brand:
    color: "#0871ab"
  copyright:
    owner:
      text: 欧雷
      url: https://linxoid.com/ourai
    period:
      start: 2015
  header:
    navs:
      - text: 文档
        url: /zh/guides/
      - text: 博客
        url: /zh/posts/
      - text: 关于
        children:
          - text: 本站
            url: /zh/about/
          - text: 作者
            url: https://linxoid.com/ourai
          - text: GitHub
            url: https://github.com/lime-theme
    navbar:
      placement: right
  footer:
    partial: _local/partials/footer
    links:
      - text: 关于
        url: /zh/about/
      - text: 资助
        url: /zh/about/#donation

ksio:
  defaults:
    layout:
      page:
        values:
          ksio_asset_css:
            - stylesheets/ksio/vendors/share
          ksio_asset_js:
            - javascripts/ksio/vendors/share.min
            - javascripts/ksio/components/page
            - javascripts/ksio/components/toc
      post:
        extends: page
      ksio/doc:
        values:
          ksio_asset_css:
            - stylesheets/ksio/vendors/share
          ksio_asset_js:
            - javascripts/ksio/vendors/share.min
            - javascripts/ksio/components/page
            - javascripts/ksio/components/toc
      _local/layouts/index:
        values:
          ksio_asset_css:
            - stylesheets/local/pages/index
    page:
      - scope:
          path: ""
          type: posts
        values:
          ksio_asset_css:
            - stylesheets/local/pages/post
          ksio_asset_js:
            - javascripts/ksio/vendors/jquery.timeago
            - javascripts/ksio/vendors/jquery.timeago.zh-CN
            - javascripts/ksio/initializers/time
            - javascripts/ksio/vendors/jquery.lazyload
            - javascripts/ksio/initializers/lazyload
      - scope:
          path: ""
          type: knosys
        values:
          layout: ksio/doc
          ksio_asset_css:
            - stylesheets/local/syntax-highlighting
            - stylesheets/local/pages/post
            - stylesheets/local/pages/doc
          ksio_asset_js:
            - javascripts/ksio/vendors/jquery.timeago
            - javascripts/ksio/vendors/jquery.timeago.zh-CN
            - javascripts/ksio/initializers/time
            - javascripts/ksio/vendors/jquery.lazyload
            - javascripts/ksio/initializers/lazyload
          repo: default/cookbook

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
